networks:
  proxiable:
    name: proxiable
    external: true

services:
  portfolio-app-dev:
    container_name: portfolio-app-dev
    image: portfolio-app:dev
    environment:
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxiable