networks:
  proxiable:
    name: proxiable
    external: true

services:
  portfolio-app:
    container_name: portfolio-app
    image: portfolio-app:latest
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxiable
